"""update user, task

Revision ID: 8483a416f520
Revises: a7d93c5ef893
Create Date: 2022-10-14 14:30:40.102104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8483a416f520'
down_revision = 'a7d93c5ef893'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
